### ISSUE TITLE
linux 实现ipa 签名似乎有 Python2.7 的实现

### ISSUE THREAD

**Issue by MartinLau7** [kitsudog/ios_ci#3]
**可以通过[这个仓库](https://github.com/apperian/isign)实现 linux 签名**
降低对 macOS 上的依赖。

**Comment by kitsudog** [comment]
http://appuploader.net/
可以关注一下这个团队
他们专注于跨平台的打包
商业收费的
所以好处是短时间内不会没人维护

毕竟iOS是不断有人维护的
一劳永逸的做法想必不存在

**Comment by MartinLau7** [comment]
这个团队用 java 太麻烦，我最后自己实现了
